CREATE TABLE product
(
    ID          BIGINT    NOT NULL PRIMARY KEY,
    PRICE       DECIMAL,
    TAX_PERCENT INTEGER,
    MODIFIED_AT TIMESTAMP NOT NULL,
    CREATED_AT  TIMESTAMP NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS product_i18n_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE product_i18n
(
    ID          BIGINT      NOT NULL PRIMARY KEY,
    PRODUCT_ID  INTEGER     NOT NULL,
    LOCALE      VARCHAR(20) NOT NULL,
    NAME        VARCHAR(20) NOT NULL,
    DESCRIPTION TEXT,
    MODIFIED_AT TIMESTAMP   NOT NULL,
    CREATED_AT  TIMESTAMP   NOT NULL,
    CONSTRAINT product_id_locale_unique UNIQUE (product_id, locale)
);